config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'sessions' }, :skip => :registrations
  devise_for :customers, :hosts,  controllers: { registrations: 'users/registrations'}, :skip => :sessions

  resources :spots

  get '/account-selection', to: 'pages#account_selection'
  get '/users/:id', to: 'pages#profile'
  get '/mySpots', to: 'pages#mySpots'

  mount Commontator::Engine => '/commontator'

end

app/models/spot.rb
class Spot < ApplicationRecord
    belongs_to :host
    has_many_attached :images

    acts_as_commontable dependent: :destroy

    validates :address, :price, :description, presence: true
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    # commontator_thread_show(@spot)
  end

  # GET /spots/new
  def new
    @spot = current_user.spots.build
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = current_user.spots.build(spot_params)
    add_default_image(@spot)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:address, :description, :price, images: [])
    end

    def add_default_image(spot)
      unless spot.images.attached?
        spot.images.attach(
            io: File.open(Rails.root.join('app', 'assets', 'images', 'Placeholder.png')),
            filename: 'Placeholder.png', content_type: 'image/png'
        )
        end
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_with(model: spot, local: true) do |form| %>
  <% if spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-primary">
<div class="panel-heading"><strong>NEW SPOT</strong></div>
  <div class="panel-body">

    <div class="form-inputs">
    
      <%= form.label :address %>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-map-marker"></i></span>
        <%= form.text_field :address, placeholder:"Address", autofocus: true, class: "form-control" %>
      </div>
      <br>

      <%= form.label :description %>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
        <%= form.text_field :description, class: "form-control" %>
      </div>
      <br>

      <%= form.label :price %>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-usd"></i></span>
        <%= form.number_field :price, class: "form-control" %>
      </div>
      <br>

      <div class="form-group">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true %>
      </div>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class:"btn btn-lg btn-primary btn-block" %>
    </div>

    <% end %>
  </div>
</div>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'BACK', :back, class:"btn btn-sm btn-warning", style:"font-weight: bold;" %>

app/views/spots/index.html.erb
<h1 class="text-center">Spots</h1>

<ul class="spot-list">
<% @spots.each do |spot| %>

  <li>
    <header><%= link_to image_tag(spot.images[0], style:"width: 100%; height: 100%; border-top-left-radius: 1rem; border-top-right-radius: 1rem"), spot%></header>
    <strong><%= spot.address%></strong>
    <p>Price: $<%= spot.price %></p>
  </li>
<%end%>

app/views/spots/new.html.erb
<%= render 'form', spot: @spot %>

<%= link_to 'BACK', spots_path , class: "btn btn-sm btn-warning", style:"font-weight: bold"%> 

app/views/spots/show.html.erb
<div style="width: 600px; height: 304px; border: 2px solid grey">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @spot.images.each_with_index do |photo, n| %>
        <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
      <% end %>
    </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag(@spot.images.first, style:"max-width: 550px; max-height: 300px")%>
    </div>
    <% @spot.images.drop(1).each do |photo| %>
      <div class="item">
        <%= image_tag(photo, style:"width: 100%; height: 300px") %>
      </div>
    <% end %>
  </div>

  <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<p>
  <strong>Address:</strong>
  <%= @spot.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spot.description %>
</p>

<p>
  <strong>Price: $</strong><%=@spot.price %>
</p>

<p>
  <%= link_to 'Company profile', "/users/#{@spot.host_id}", class:"btn btn-primary", style:"font-weight: bold;" %>
  <br>
</p>

<%= commontator_thread(@spot) %>
<br>


<% if user_signed_in? %>
  <% if current_user == @spot.host || current_user.admin? %>
    <%= link_to 'EDIT', edit_spot_path(@spot), class:"btn btn-primary" %> |
    <%= link_to 'DELETE', @spot, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |
  <% end %>
<% end %>
<%= link_to 'BACK', spots_path, class:"btn btn-sm btn-warning", style:"font-weight: bold;" %>