config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'sessions' }, :skip => :registrations
  devise_for :customers, :hosts,  controllers: { registrations: 'users/registrations'}, :skip => :sessions

  resources :spots

  get '/account-selection', to: 'pages#account_selection'
  get '/users/:id', to: 'pages#profile'
  get '/mySpots', to: 'pages#mySpots'

  mount Commontator::Engine => '/commontator'

end

app/views/pages/account_selection.html.erb
<h1 class="text-center"> How would you like to use AirUnB? </h1>
<br>
<div class="text-center">
    <%= link_to 'FOR ME', new_customer_registration_path, class:"btn btn-primary" %>
    <%= link_to 'FOR BUSSINESS', new_host_registration_path, class:"btn btn-primary" %>
</div>

app/views/pages/home.html.erb
<h1 class="text-center" > Find the best spot </h1>

<div style="display: flex; flex-direction: row; justify-content: space-evenly; padding-top: 2rem">
    <% @spots.each do |spot| %>
        <div style="width: 250px; height: auto; border: 1px solid grey">
            <%= link_to image_tag(spot.images.sample, style:"width: 100%; height: 100%"), spot %>
        </div>
    <% end %>
</div>

<br>

<div class="text-center" style="padding-top: 3rem">
    <%= link_to "SHOW MORE SPOTS", spots_path, class:"btn btn-lg btn-primary", style:"font-weight: bold;"%>
</div>

app/views/pages/mySpots.html.erb
<div class="text-center">
  <% if @spots.empty? %>
    <h1>You don't have any Spots</h1>
  <% end %>
</div>

<ul class="spot-list">
<% @spots.each do |spot| %>
  <li>
    <header><%= link_to image_tag(spot.images[0], style:"width: 100%; height: 100%; border-top-left-radius: 1rem; border-top-right-radius: 1rem"), spot%></header>
    <strong><%= spot.address%></strong>
    <p>Price: $<%= spot.price %></p>
  </li>
<%end%>

app/views/pages/profile.html.erb
<div class="panel panel-primary">
<div class="panel-heading"><strong><%= @user.company_name.blank? ? @user.first_name.camelize+' '+ @user.last_name.camelize : @user.company_name.camelize %></strong></div>

    <div style="width: 250px; height: 250px">
        <%= image_tag @user.avatar, style:"width: 100%; height: 100%;" %>
    </div>

    <div>
        <%= @user.email %>
    <div>

    <div>
        <%= @user.phone.blank? ? "No phone" : @user.phone %>
    </div>
</div>
</div>