config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'sessions' }, :skip => :registrations
  devise_for :customers, :hosts,  controllers: { registrations: 'users/registrations'}, :skip => :sessions

  resources :spots

  get '/account-selection', to: 'pages#account_selection'
  get '/users/:id', to: 'pages#profile'
  get '/mySpots', to: 'pages#mySpots'

  mount Commontator::Engine => '/commontator'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "AirUnB", root_path %></div>
        <nav class="collapse navbar-collapse">
          <% if user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <% if can? :create, Spot %>
                  <li><%= link_to 'NEW SPOT', new_spot_path %></li>
              <% end %>
              <li><%= link_to 'ACCOUNT', "/#{current_user.type.downcase}s/edit" %></li>
              <li><%= link_to 'SIGN OUT', destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li class="nav-item"><%= link_to 'SIGN UP', '/account-selection' %></li>
              <li class="nav-item"><%= link_to 'LOGIN', new_user_session_path %></li>
            </ul>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
    <div id="content" class="conteiner ">
    <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <% [*value].each do |message| %>  
            <%= message %></br>
          <% end %>
        </div>
    <% end %>
      <%= yield %>
    </div>
  </div>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script>
    $( document ).ready(function(){
    $('#mycarousel').carousel();
    });
  </script>
</body>
</html>